=== 256p/org.aspectj/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test+)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!ELEMENT ajc-test (compile, (compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,file*,message*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >

   <!ELEMENT file (#PCDATA)>
   <!ATTLIST file path CDATA #IMPLIED >

   <!ELEMENT message (#PCDATA)>
   <!ATTLIST message kind (error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #REQUIRED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc187/ajc187.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

<ajc-test dir="bugs187/469889" title="broken java">
<!-- 
<compile files="A.java B.java AbstractA.java BImpl.java Main.java" options="-1.8"/>
-->
<compile files="Code.java" options="-1.8"/>
<run class="Code">
<stdout>
<line text="B"/>
</stdout>
</run>
</ajc-test>


<ajc-test dir="bugs187/470633" title="lambda">
<compile files="Maps.java" options="-1.8"/>
</ajc-test>

<ajc-test dir="bugs187/474165" title="anno conversion">
<compile files="B.java" options="-XhasMember -1.8 -showWeaveInfo">
<message kind="weave" text="Extending interface set for type 'B' (B.java) to include 'java.io.Serializable' (B.java)"/>
</compile>
<run class="B"></run>
</ajc-test>

</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc1611/ajc1611.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

  <ajc-test dir="bugs1611/pr328840" title="pr328840">
    <compile files="Wibble.aj" options="-1.5 -showWeaveInfo">
    <message kind="weave" text="Join point 'field-get(XX Song.i)' in Type 'Song' (Wibble.aj:26) advised by before advice from 'Wibble' (Wibble.aj:9)"/>
    <message kind="weave" text="'XX i' of type 'Song' (Wibble.aj) is annotated with @Foo field annotation from 'Wibble' (Wibble.aj:7)"/>
    </compile>
    <run class="Wibble">
    <stdout>
    <line text="@Foo()"/>
    </stdout></run>
  </ajc-test>
  
  <ajc-test dir="bugs1611/pr332388" title="pr332388">
     <compile files="M.java" outjar="M.jar" options="-1.5"/>
     <compile files="A.java B.java" classpath="M.jar" outjar="AB.jar" options="-1.5"/>
     <compile files="MyAspect.java" outjar="aspects.jar" options="-1.5"/>
     <compile files="" aspectpath="aspects.jar" inpath="AB.jar" options="-1.5">
     <message kind="error" text="Unable to find type for generic bound.  Missing type is M [Xlint:cantFindType]"/>
     </compile>
  </ajc-test>
  
  <ajc-test dir="bugs1611/pr333469" title="pr333469">
     <compile files="MyList.java MyList_Serializable.java" options="-1.5"/>
     <run class="MyList">
     <stdout><line text="ser=1"/></stdout>
     </run>
  </ajc-test>
  
  <ajc-test dir="bugs1611/pr332388_2" title="pr332388 - 2">
     <compile files="M.java" outjar="M.jar" options="-1.5"/>
     <compile files="A.java" classpath="M.jar" outjar="A.jar" options="-1.5"/>
     <compile files="MyAspect.java" outjar="aspects.jar" options="-1.5"/>
     <compile files="" aspectpath="aspects.jar" inpath="A.jar" options="-1.5">
     <message kind="error" text="Unable to find type (for bound): M [Xlint:cantFindType]"/>
     </compile>
  </ajc-test>
  
</suite>

=== 256p/org.aspectj/docs/sandbox/sandbox-test.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">
<!-- ../ path when running, ../../ when editing? -->


<!-- Notes
	
	- test titles should be prefixed with the corresponding 
	  sample anchor/label, and suffixed to be unique.
	  
	- take care to keep error line numbers in sync with sources	
	
	TODO
	- verify that RunTime and RuntimeWrites throw Errors	
	- harness bug: errStreamIsError not false when not forked; fork?
	- check output/error stream against expected
	- verify api-clients, using access to aspectjtools.jar...
	   
-->
<suite>
		
	<ajc-test dir="common" title="declares-* default declares">
		<compile 
			argfiles="company.lst"
			files="declares/Declares.java">
			<message 
				kind="error" 
				file="Main.java"
				line="15" 
				text="Factory"/>
			<message 
				kind="warning" 
				file="Main.java"
				line="30" 
				text="throw"/>
			<message 
				kind="warning" 
				file="Main.java"
				line="31" 
				text="handles"/>
			</compile>
		</ajc-test>

	<ajc-test dir="common" 
		title="ensure company compiles and runs without aspects">
		<compile argfiles="company.lst"/>
		<run class="com.company.app.Main"/>
	</ajc-test>

	<ajc-test dir="common" title="language-initialization">
		<compile files="language/Initialization.java"/>
		<run class="language.Initialization" 
			errStreamIsError="true"/>
		</ajc-test>
	
	<ajc-test dir="common" title="language-*Context">
		<compile files="language/Context.java"/>
		<run class="language.Context" />
		</ajc-test>

	<ajc-test dir="common" title="language-cflowRecursionBasic">
		<compile files="language/ControlFlow.java"/>
		<run class="language.ControlFlow"/>
		</ajc-test>


	<ajc-test dir="common" title="tracing-simpleLogging">
		<compile 
			argfiles="company.lst"
			files="tracing/Logging.java"/>
		<run class="com.company.app.Main"/>
		</ajc-test>

	<ajc-test dir="common" title="tracing-traceJoinPoints">
		<compile 
			argfiles="company.lst"
			files="tracing/TraceJoinPoints.java,
					tracing/TraceJoinPointsBase.java,
					tracing/TraceMyJoinPoints.java"/>
		<run class="com.company.app.Main"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="declares-inoculated-*">
		<compile files="com/xerox/printing/CompileTime.java">
			<message line="20" kind="warning"/>
			<message line="24" kind="warning"/>
			<message line="33" kind="error"/>
			<message line="39" kind="error"/>
			</compile>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-roundTrip">
		<compile files="com/xerox/printing/RoundTrip.java"/>
		<run class="com.xerox.printing.RoundTrip"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-roundTrip">
		<compile files="BufferTest.java"/>
		<run class="BufferTest"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-roundTrip">
		<compile files="BufferTest.java"/>
		<run class="BufferTest"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-injectIOException">
		<compile files="Injection.java"/>
		<run class="Injection"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-injectIOException">
		<compile files="MainFailure.java"/>
		<run class="MainFailure"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-runtimeFactories">
		<compile files="RunTime.java"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-runtimeWrites">
		<compile files="RuntimeWrites.java"/>
		</ajc-test>

	<ajc-test dir="inoculated/src" title="testing-inoculated-{proxies}">
		<compile files="StubReplace.java"/>
		<run class="StubReplace"/>
		</ajc-test>

</suite>

<!--
	TODO XXX verify api-clients using aspectjtools.jar?

	<ajc-test dir="api-clients" title="api-ajde-modelWalker">
		<compile files="org/aspectj/samples/JoinPointCollector.java"
			classpath="../aj-build/dist/tools/lib/aspectjtools.jar;"/>
		<run ... />
		</ajc-test>

-->

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc172/ajc172.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

	<ajc-test dir="bugs172/pr389750" title="inconsistent class file">
      <compile files="Code.aj" options="-1.5">
      </compile>
      <compile files="Clazz.java" options="-1.5"/>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389750" title="inconsistent class file 2">
      <compile files="Code2.aj" outjar="azpect.jar" options="-1.5">
      </compile>
      <compile files="Clazz2.java" aspectpath="azpect.jar" options="-1.5"/>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389750" title="inconsistent class file 3">
      <compile files="Code3.aj" outjar="azpect.jar" options="-1.5">
      </compile>
      <compile files="Clazz3.java" aspectpath="azpect.jar" options="-1.5"/>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389750" title="inconsistent class file 4">
      <compile files="Code4.aj" outjar="azpect.jar" options="-1.5">
      </compile>
      <compile files="Clazz4.java" aspectpath="azpect.jar" options="-1.5"/>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389752" title="annotation value error 1">
      <compile files="Code.java" options="-1.5">
      	<message kind="error" text="Invalid annotation value 'AA', expected enum value"/>
      </compile>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389752" title="annotation value error 2">
      <compile files="Code2.java" options="-1.5">
      	<message kind="error" text="Invalid annotation value 'AA', expected enum value"/>
      </compile>
    </ajc-test>
    
	<ajc-test dir="bugs172/pr389752" title="annotation value error 3">
      <compile files="Code3.java" options="-1.5">
      	<message kind="error" text="Invalid annotation value 'AA', expected enum value"/>
      </compile>
    </ajc-test>

</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/model/model.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- Model and Hierarchy Tests -->
<suite>

    <ajc-test dir="model/pr145963_1" title="sourcelocation and jar file">
      <compile files="C.java, SourceAspect.aj" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	  </compile>
    </ajc-test>

    <ajc-test dir="model/pr145963_2" title="sourcelocation and class file">
      <compile files="C.java, SourceAspect.aj" aspectpath="pkg" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	  </compile>
    </ajc-test>

   <ajc-test dir="model/pr145963_3" title="aspect in default package">
      <compile files="C.java" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	</compile>
    </ajc-test>

   <ajc-test dir="model/pr145963_4" title="aspect in java file">
      <compile files="C.java" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	</compile>
    </ajc-test>


</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc162/ajc162.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.2 Tests -->
<suite>

	<ajc-test dir="bugs162/pr239441" title="annotation decp">
    	<compile files="Test3.java SampleAspect.java" options="-1.5 -showWeaveInfo -XhasMember">
    	</compile>
    </ajc-test>    
    
	<ajc-test dir="bugs162/pr238992" title="annotation value decp">
    	<compile files="Foo.java" options="-1.5 -showWeaveInfo">
    	  <message kind="weave" text="Extending interface set for type 'Goo'"/>
    	</compile>
    	<run class="Foo"/>
    </ajc-test>    
    
	<ajc-test dir="bugs162/pr238992" title="annotation value decp - 2">
    	<compile files="Foo2.java" options="-1.5 -showWeaveInfo">
    	  <message kind="weave" text="Extending interface set for type 'Goo'"/>
    	  <message kind="weave" text="Extending interface set for type 'Hoo'"/>
    	</compile>
    	<run class="Foo2"/>
    </ajc-test>    
    
	<ajc-test dir="bugs162/pr238992" title="annotation value decp - 3">
    	<compile files="Foo3.java" options="-1.5 -showWeaveInfo">
    	  <message kind="weave" text="Extending interface set for type 'Goo'"/>
    	</compile>
    	<run class="Foo3"/>
    </ajc-test>    
    
	<ajc-test dir="bugs162/pr238992" title="annotation value decp - 4">
    	<compile files="Foo4.java" options="-1.5 -showWeaveInfo">
    	  <message kind="weave" text="Extending interface set for type 'Goo'"/>
    	  <message kind="weave" text="Extending interface set for type 'Hoo'"/>
    	</compile>
    	<run class="Foo4"/>
    </ajc-test>    

</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc164/ajc164.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>
    
    <ajc-test dir="bugs163/pr164016" title="ataspectj decp 164016">
      <compile files="Code.aj" options="-1.5"/>
      <run class="test.Code"/>
    </ajc-test>    
    
    <ajc-test dir="bugs163/pr258788" title="ataspectj decp 258788">
      <compile files="NameAware.java NameManager.java NameManagerImpl.java StartClass.java TargetClass.java TestAspect.java" options="-1.5"/>
      <run class="com.StartClass"/>
    </ajc-test>    
    
    <ajc-test dir="bugs163/pr213751" title="mixed styles">
   	  <compile files="Foo.java" options="-emacssym -1.5"/>
    </ajc-test>
    
</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc150/ataspectj/syntax.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>
<suite>

    <ajc-test dir="java5/ataspectj" title="SimpleBefore">
        <compile files="SimpleBefore.java" options="-1.5 -showWeaveInfo -XnoInline">
            <message kind="weave" text="(SimpleBefore.java:23) advised by before advice from 'SimpleBefore$X' (SimpleBefore.java:1)"/>
        </compile>
        <run class="SimpleBefore"/>
        <compile files="SimpleBefore.java" options="-1.5 -showWeaveInfo -XnoInline -Xdev:NoAtAspectJProcessing">
            <message kind="weave" text="(SimpleBefore.java:23) advised by before advice from 'SimpleBefore$X' (SimpleBefore.java:1)"/>
        </compile>
        <run class="SimpleBefore"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="SimpleAfter">
        <compile files="SimpleAfter.java" options="-1.5 -showWeaveInfo -XnoInline">
            <message kind="weave" text="(SimpleAfter.java:13) advised by after advice from 'SimpleAfter$X'"/>
        </compile>
        <run class="SimpleAfter"/>
        <compile files="SimpleAfter.java" options="-1.5 -showWeaveInfo -XnoInline -Xdev:NoAtAspectJProcessing">
            <message kind="weave" text="(SimpleAfter.java:13) advised by after advice from 'SimpleAfter$X'"/>
        </compile>
        <run class="SimpleAfter"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="singletonAspectBindings">
        <compile files="ataspectj/SingletonAspectBindingsTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline"/>
        <run class="ataspectj.SingletonAspectBindingsTest"/>
        <compile files="ataspectj/SingletonAspectBindingsTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.SingletonAspectBindingsTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="CflowTest">
        <compile files="ataspectj/CflowTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.CflowTest"/>
        <compile files="ataspectj/CflowTest.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.CflowTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="PointcutReferenceTest">
        <compile files="ataspectj/PointcutReferenceTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.PointcutReferenceTest"/>
        <compile files="ataspectj/PointcutReferenceTest.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.PointcutReferenceTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="XXJoinPointTest">
        <compile files="ataspectj/XXJoinPointTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.XXJoinPointTest"/>
        <compile files="ataspectj/XXJoinPointTest.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.XXJoinPointTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="PrecedenceTest">
        <compile files="ataspectj/PrecedenceTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.PrecedenceTest"/>
        <compile files="ataspectj/PrecedenceTest.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.PrecedenceTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="AfterXTest">
        <compile files="ataspectj/AfterXTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.AfterXTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="IfPointcutTest">
        <compile files="ataspectj/IfPointcutTest.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.IfPointcutTest"/>
        <!-- FIXME AV - Adrian in JDT stuff -->
<!--        <compile files="ataspectj/IfPointcutTest.java,ataspectj/TestHelper.java" options="-1.5"/>-->
<!--        <run class="ataspectj.IfPointcutTest"/>-->
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="IfPointcut2Test">
        <compile files="ataspectj/IfPointcut2Test.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.IfPointcut2Test"/>
        <!-- FIXME AV - Adrian in JDT stuff -->
<!--        <compile files="ataspectj/IfPointcut2Test.java,ataspectj/TestHelper.java" options="-1.5"/>-->
<!--        <run class="ataspectj.IfPointcut2Test"/>-->
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="BindingTest">
        <compile files="ataspectj/BindingTest.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.BindingTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="BindingTest no inline">
        <compile files="ataspectj/BindingTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline"/>
        <run class="ataspectj.BindingTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="PerClause">
        <compile files="ataspectj/PerClauseTest.java,ataspectj/PerClauseTestAspects.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.PerClauseTest"/>
        <compile files="ataspectj/PerClauseTest.java,ataspectj/PerClauseTestAspects.java,ataspectj/TestHelper.java" options="-1.5"/>
        <run class="ataspectj.PerClauseTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="AroundInlineMunger -XnoInline">
        <compile files="ataspectj/AroundInlineMungerTest.java,ataspectj/AroundInlineMungerTestAspects.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline -Xdev:NoAtAspectJProcessing -Xlint:ignore"/>
        <run class="ataspectj.AroundInlineMungerTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="AroundInlineMunger">
        <compile files="ataspectj/AroundInlineMungerTest.java,ataspectj/AroundInlineMungerTestAspects.java,ataspectj/TestHelper.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore"/>
        <run class="ataspectj.AroundInlineMungerTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="AroundInlineMunger2">
        <compile files="ataspectj/AroundInlineMungerTest2.aj,ataspectj/AroundInlineMungerTestAspects2.aj,ataspectj/TestHelper.java" options="-1.5 -Xlint:ignore"/>
        <run class="ataspectj.AroundInlineMungerTest2"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="Deow">
        <compile files="ataspectj/DeowTest.java" options="-1.5">
            <message kind="warning" line="28" text="call hello"/>
            <message kind="error" line="29" text="call hi"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="singletonInheritance">
        <compile files="ataspectj/SingletonInheritanceTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline"/>
        <run class="ataspectj.SingletonInheritanceTest"/>
        <compile files="ataspectj/SingletonInheritanceTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.SingletonInheritanceTest"/>
    </ajc-test>

    <ajc-test dir="java5/ataspectj" title="perClauseInheritance">
<!--        <compile files="ataspectj/PerClauseInheritanceTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline"/>-->
<!--        <run class="ataspectj.PerClauseInheritanceTest"/>-->
        <compile files="ataspectj/PerClauseInheritanceTest.java,ataspectj/TestHelper.java" options="-1.5 -XnoInline -Xdev:NoAtAspectJProcessing"/>
        <run class="ataspectj.PerClauseInheritanceTest"/>
    </ajc-test>

</suite>
