=== 256p/org.aspectj/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test+)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!ELEMENT ajc-test (compile, (compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,file*,message*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >

   <!ELEMENT file (#PCDATA)>
   <!ATTLIST file path CDATA #IMPLIED >

   <!ELEMENT message (#PCDATA)>
   <!ATTLIST message kind (error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #REQUIRED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc160/annotationValueMatching.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.0 Annotation Value Matching Tests -->
<suite>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 1">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest1.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest1.m())' in Type 'a.EnumTest1' (EnumTest1.java:9) advised by before advice from 'a.EnumTest1' (EnumTest1.java:13)"/>
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest1.o())' in Type 'a.EnumTest1' (EnumTest1.java:11) advised by before advice from 'a.EnumTest1' (EnumTest1.java:13)"/>
     </compile>
     <run class="a.EnumTest1"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 2">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest2.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest2.m())' in Type 'a.EnumTest2' (EnumTest2.java:9) advised by before advice from 'a.EnumTest2' (EnumTest2.java:13)"/>
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest2.o())' in Type 'a.EnumTest2' (EnumTest2.java:11) advised by before advice from 'a.EnumTest2' (EnumTest2.java:13)"/>
     </compile>
     <run class="a.EnumTest2"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 3">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest3.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest3.m())' in Type 'a.EnumTest3' (EnumTest3.java:9) advised by before advice from 'a.EnumTest3' (EnumTest3.java:13)"/>
     </compile>
     <run class="a.EnumTest3"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="broken - 1">
     <compile options="-1.5 -showWeaveInfo" files="Broken1.java"> 
       <message kind="error" line="28" text="Invalid annotation value 'a', expected enum value"/>
     </compile>
   </ajc-test>
   
   <ajc-test dir="features160/annotationValueMatching" title="parsing">
     <compile options="-1.5 -showWeaveInfo Parsing.java"/>
   </ajc-test>
      
   <ajc-test dir="features160/annotationValueMatching" title="simple">
     <compile options="-1.5 -showWeaveInfo Simple.java">
       <message kind="weave" text="Join point 'method-execution(void Marked.b())' in Type 'Marked' (Simple.java:18) advised by before advice from 'X' (Simple.java:28)"/>
       <message kind="weave" text="Join point 'method-execution(void Marked.c())' in Type 'Marked' (Simple.java:21) advised by before advice from 'X' (Simple.java:28)"/>
     </compile>       
   </ajc-test>
   
</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc151/ajc151.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.5.1 Tests -->
<suite>
    
    <ajc-test dir="bugs151" title="member types in generic types">
        <compile files="pr122458.aj" options="-1.5 -emacssym"/>
    </ajc-test>
    
    <ajc-test dir="bugs151" title="member types in generic types - 2">
        <compile files="pr122458_2.aj" options="-1.5 -emacssym"/>
        <run class="pr122458_2"/>
    </ajc-test>
    
    <ajc-test dir="bugs151/pr123695" title="Internal nullptr exception with complex declare annotation">
        <compile files="InjectName.java,Main.java,MarkMyMethods.java,MarkMyMethodsAspect.java,NameAspect.java,Named.java,Read.java,Write.java" options="-1.5"/>
    </ajc-test>
    
    <ajc-test dir="bugs151/pr124105" title="hasMember problems with packages">
        <compile files="com/test/IOption.java,com/test/IXOption.java,com/test/IYOption.java,com/test/IZOption.java,com/test/MyBrokenXOption.java,com/test/MyXOption.java,com/test/OptionAspect.aj,com/test/OptionType.java" options="-1.5 -XhasMember">
          <message kind="error" line="4" text="IOption implementations must provide a constructor which accepts an OptionType"/>
        </compile>
    </ajc-test>
    

</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc152/injar.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.5.2 Tests -->
<suite>

    <ajc-test dir="bugs152/pr145963" title="advice and deow">
      <compile files="ClassForAspectPath.java" aspectpath="adviceAndDeow.jar" options="-emacssym">
		<message kind="warning" line="9" text="There should be no printlns"/>
	  </compile>
    </ajc-test>

    <ajc-test dir="bugs152/pr145963" title="ensure advice label is correct">
      <compile files="C.java" aspectpath="adviceLabels.jar" options="-emacssym"/>
    </ajc-test>
    
    <ajc-test dir="bugs152/pr145963" title="aspect in default package">
      <compile files="C.java" aspectpath="aspectInDefaultPackage.jar" options="-emacssym"/>
    </ajc-test>

</suite>

=== 256p/org.aspectj/tests/ajcHarnessTests.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">

<!--
    To log unexpected results, run
        with -logPass -ajctestRequireKeywords=expect-fail
     or with -logFail -ajctestSkipKeywords=expect-fail

     Also pick out "incremental" keyword for incremental tests.
-->
<suite>

    <ajc-test dir="noSuchDir"
      title="no such directory - report as error (AjcTest specification)"
     keywords="expect-fail">
        <compile files="NoSuchFile.java"/>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error">
        <compile files="ErrorTest.java">
            <message kind="error" line="5"/>
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error, with filenames">
        <compile files="ErrorTest.java">
            <message kind="error" line="5" file="ErrorTest.java"/>
            <message kind="error" line="6" file="ErrorTest.java"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error, three expected"
     keywords="expect-fail">
        <compile files="ErrorTest.java">
            <message kind="error" line="5"/>
            <message kind="error" line="6"/>
            <message kind="error" line="8"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error, one unexpected"
     keywords="expect-fail">
        <compile files="ErrorTest.java">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error, one with with error line wrong"
     keywords="expect-fail">
        <compile files="ErrorTest.java">
            <message kind="error" line="5"/>
            <message kind="error" line="7" text="Wrong line number"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="2 error, one with with kind wrong"
     keywords="expect-fail">
        <compile files="ErrorTest.java">
            <message kind="error" line="5"/>
            <message kind="warning" line="6"/>
        </compile>
    </ajc-test>
    
    <ajc-test dir="harness"
      title="1 warning">
        <compile files="WarningTest.java">
            <message kind="warning" line="14"/>
        </compile>
    </ajc-test>
    
    <ajc-test dir="harness"
      title="1 warning with kind wrong"
     keywords="expect-fail">
        <compile files="WarningTest.java">
            <message kind="error" line="14"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness"
      title="1 warning with line wrong"
     keywords="expect-fail">
        <compile files="WarningTest.java">
            <message kind="warning" line="15"/>
        </compile>
    </ajc-test>

    <ajc-test dir="harness" title="checks and events, failed to specify 6 expected fails"
     keywords="expect-fail">
        <compile files="TestTesterFail.java"/>
        <run class="TestTesterFail"/>
    </ajc-test>

    <ajc-test dir="harness" title="one missing note"
     keywords="expect-fail">
        <compile files="TesterNotesFail.java"/>
        <run class="TesterNotesFail"/>
    </ajc-test>

    <ajc-test dir="harness" title="checks and events, all should pass">
        <compile files="TestTester.java"/>
        <run class="TestTester"/>
    </ajc-test>

    <ajc-test dir="harness" title="event files">
        <compile files="TestTesterFile.java"/>
        <run class="TestTesterFile"/>
    </ajc-test>

    <ajc-test dir="harness" title="compile and run, no tester required">
        <compile files="TestNoTester.java"/>
        <run class="TestNoTester" skipTester="true"/>
    </ajc-test>

    <ajc-test dir="harness/classpathTest"
      title="specify jars and directories on classpath"
      keywords="purejava">
        <compile classpath="classesDir,jars/required.jar" 
                 files="Main.java"/>
        <run class="Main"/>
    </ajc-test>

    <ajc-test dir="harness/classpathTest"
      title="specify aspectpath and classpath jars and directories">
        <compile classpath="classesDir,jars/required.jar"
                 aspectpath="jars/requiredAspects.jar"
                 files="AspectMain.java"/>
        <run class="AspectMain"/>
    </ajc-test>

    <ajc-test dir="harness"  keywords="incremental"
    		title="minimal purejava sourceroots test">
        <compile sourceroots="sourceroot"/>
		<run class="packageOne.Main"/>
    </ajc-test>

    <ajc-test dir="harness"  keywords="incremental"
    		title="test of dual sourceroots with aspects">
        <compile sourceroots="sourceroot,sourceroot2"/>
		<run class="packageOne.Main"/>
    </ajc-test>

    <ajc-test dir="harness"  keywords="incremental"
    		title="minimal incremental purejava sourceroots test"
    	comment="inc-22 generates new event, expected after">
        <compile options="-incremental" 
        	sourceroots="sourceroot-inc"/>
		<run class="packageOne.Main"/>
        <inc-compile tag="22"/> 
		<run class="packageOne.Main" 
		   options="new-event"/>
    </ajc-test>

    <ajc-test dir="harness"  keywords="incremental"
    		title="rebuild minimal incremental purejava sourceroots test"
    	comment="inc-22 generates new event, expected after">
        <compile options="-incremental" 
        	sourceroots="sourceroot-inc"/>
		<run class="packageOne.Main"/>
        <inc-compile tag="22"/>
		<run class="packageOne.Main" 
		   options="new-event"/> 

        <compile options="-incremental" 
            reuseCompiler="true"
        	sourceroots="sourceroot-inc"/>
		<run class="packageOne.Main"/>
        <inc-compile tag="22"/>
		<run class="packageOne.Main" 
		   options="new-event"/>
    </ajc-test>
    
    <ajc-test dir="harness"  keywords="incremental"
    		title="rebuild fresh-same minimal incremental purejava sourceroots test"
    	comment="inc-22 generates new event, expected after">
        <compile options="-incremental" 
        	sourceroots="sourceroot-inc"/>
		<run class="packageOne.Main"/>
        <inc-compile tag="22"/> 
		<run class="packageOne.Main" 
		   options="new-event"/> 

        <inc-compile tag="same" fresh="true" />
		<run class="packageOne.Main" 
		   options="new-event"/> <!-- now expect new-event -->
    </ajc-test>
    
    <ajc-test dir="harness"  keywords="incremental"
    		title="rebuild fresh-updated minimal incremental purejava sourceroots test"
    	comment="inc-22 generates new event, expected after">
        <compile options="-incremental" 
        	sourceroots="sourceroot-inc"/>
		<run class="packageOne.Main"/>

        <inc-compile tag="22" fresh="true" /> 
		<run class="packageOne.Main" 
		   options="new-event"/> 
    </ajc-test>

    <ajc-test dir="incremental/stringliteral"  
    		title="incrementally change only string literal size">
        <compile staging="true" options="-incremental" 
        	sourceroots="src"/>
		<run class="packageOne.Main"
			options="in packageOne.Main.main(..),
					 before main packageOne.Main"/>
        <inc-compile tag="20">
        	<dir-changes updated="packageOne.Main"/>
        </inc-compile>
		<run class="packageOne.Main"
			options="in longer packageOne.Main.main(..),
					 before main packageOne.Main"/>
    </ajc-test>
    
</suite>

=== 256p/org.aspectj/tests/src/org/aspectj/systemtest/ajc165/ajc165.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<suite>

   <ajc-test dir="bugs165/pr265356" title="annotation style message positions">
     <compile files="Main.java" options="-1.5">
       <message kind="warning" line="11"/>
       <message kind="warning" line="13"/>
       <message kind="warning" line="14"/>
     </compile>
   </ajc-test>

   <ajc-test dir="bugs165/pr271169" title="around call npe">
     <compile files="HypChecksums.java" options="-1.5"/>
   </ajc-test>

</suite>
